services:
  app: 
    container_name: serviceavailabilitycheckapi
    build: .
    env_file: .api.env
    hostname: serviceavailabilitycheck
    restart: unless-stopped
    ports:
    - "${PORT}:${PORT}"