services:
  app: 
    container_name: serviceavailabilitycheckapi
    build: .
    env_file: .api.env
    hostname: serviceavailabilitycheck
    restart: unless-stopped
    ports:
    - "${PORT}:${PORT}"

  database:
    image: mariadb
    env_file: .api.env
    ports:
    - "${DBPORT}:${DBPORT}"
    restart: unless-stopped